
s=str(input("Nhập chuỗi s:"))
s_sub=str(input("Nhập chuỗi con s_sub:"))
s_find=str(input("Nhập chuỗi tìm s_find:"))
s_replace=str(input("Nhập chuỗi thay thế s_place:"))
print("Chuỗi s là:",s)
print(str.strip(s))
print(str.capitalize(s))
print("Chuỗi sau khi loại bỏ khoảng trắng ở đầu và cuối:",str.count(sub,,[start,end]))
print("Chuỗi s sau khi được tìm kiếm và thay thế:",str.count(sub,,[start,end]))
